{
 "title": "Prosody",
 "tags": [
  "prosody",
  "xmpp"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "virtualhost", "label": "VirtualHost", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  { "title": "Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prosody\"}[$__interval])",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(process_virtual_memory_bytes{job=\"prosody\"}[$__interval])",
     "legendFormat": "Virtual"
    },
    {
     "expr": "max_over_time(process_resident_memory_bytes{job=\"prosody\"}[$__interval])",
     "legendFormat": "RSS"
    },
    {
     "expr": "max_over_time(malloc_heap_allocated_bytes{job=\"prosody\"}[$__interval])",
     "legendFormat": "Allocated ({{mode}})"
    },
    {
     "expr": "max_over_time(malloc_heap_used_bytes{job=\"prosody\"}[$__interval])",
     "legendFormat": "Used"
    },
    {
     "expr": "max_over_time(lua_heap_bytes{job=\"prosody\"}[$__interval])",
     "legendFormat": "Lua"
    },
    {
     "expr": "sum(lua_heap_bytes{job=\"prosody\"}) / (sum(prosody_mod_c2s__connections{job=\"prosody\"})+sum(prosody_mod_s2s__connections_inbound{job=\"prosody\"})+sum(prosody_mod_s2s__connections_outbound{job=\"prosody\"}))",
     "legendFormat": "Lua (per connection)"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Client-to-Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "prosody_mod_c2s__connections{type=\"c2s\"}",
     "legendFormat": "{{ip_family}} {{type}}"
    }
   ]
  },
  {
   "title": "Server-to-Server Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(prosody_mod_s2s__connections_inbound{type=\"s2sin\"}) by (ip_family)",
     "legendFormat": "{{ip_family}} s2sin"
    },
    {
     "expr": "sum(prosody_mod_s2s__connections_outbound{type=\"s2sout\"}) by (ip_family)",
     "legendFormat": "{{ip_family}} s2sout"
    }
   ]
  },
  {
   "title": "Client-to-Server Connections Encrypted",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "changes(prosody_mod_c2s__encrypted_total[$__interval])",
     "legendFormat": "{{protocol}} {{cipher}}"
    }
   ]
  },
  {
   "title": "Server-to-Server Connections Encrypted",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "changes(prosody_mod_s2s__encrypted_total[$__interval])",
     "legendFormat": "{{protocol}} {{cipher}}"
    }
   ]
  },
  { "title": "Stream Management", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Resumption Age",
   "type": "heatmap",
   "description": "How long a session has been hibernating when a client resumes it",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(le) (changes(prosody_mod_smacks__resumption_age_seconds_bucket{host=\"$virtualhost\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Stanzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(prosody_mod_smacks__tx_queued_stanzas_total{host=\"$virtualhost\"}[$__interval])",
     "legendFormat": "queued on {{host}}"
    },
    {
     "expr": "rate(prosody_mod_smacks__tx_acked_stanzas_count{host=\"$virtualhost\"}[$__interval])",
     "legendFormat": "acked on {{host}}"
    }
   ]
  },
  { "title": "Mobile optimizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Hold time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prosody_mod_csi_simple__buffer_hold_seconds_bucket{host=\"$virtualhost\"}[$__rate_interval])))",
     "legendFormat": "CSI hold seconds"
    }
   ]
  },
  {
   "title": "Flush sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(prosody_mod_csi_simple__flush_stanza_count_bucket{host=\"$virtualhost\"}[$__rate_interval])))",
     "legendFormat": "Stanzas flushed"
    }
   ]
  },
  { "title": "HTTP Upload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Upload sizes",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by(le) (changes(prosody_mod_http_file_share__upload_bytes_bucket{host=\"$virtualhost\"}[$__interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total uploads",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prosody_mod_http_file_share__total_storage_bytes{host=\"$virtualhost\"}"
    }
   ]
  }
 ]
}