#!/usr/bin/env bash

# This is just a simple script to

set -eu

DATA_DIR=./data

run() {
  if [ ! -d "${DATA_DIR:?}"/etc/prosody ]; then
    mkdir -p "${DATA_DIR:?}"/etc/prosody

    local prosody_cfg="${DATA_DIR:?}"/etc/prosody/prosody.cfg.lua
    [ -f "${prosody_cfg:?}" ] || wget -O "${prosody_cfg:?}" \
      https://raw.githubusercontent.com/prose-im/prose-pod-system/refs/heads/master/server/local/etc/prosody/prosody.cfg.lua
  fi

  if [ ! -d "${DATA_DIR:?}"/var/lib/prosody ]; then
    mkdir -p "${DATA_DIR:?}"/var/lib/prosody

    mkdir "${DATA_DIR:?}"/var/lib/prosody/example%2eorg
    touch "${DATA_DIR:?}"/var/lib/prosody/example%2eorg/cron.dat

    mkdir "${DATA_DIR:?}"/var/lib/prosody/example%2eorg/accounts
    touch "${DATA_DIR:?}"/var/lib/prosody/example%2eorg/accounts/pauline%2ecollins.dat

    mkdir "${DATA_DIR:?}"/var/lib/prosody/upload%2eprose%2elocal
    touch "${DATA_DIR:?}"/var/lib/prosody/upload%2eprose%2elocal/cron.dat
    dd if=/dev/zero of="${DATA_DIR:?}"/var/lib/prosody/upload%2eprose%2elocal/example.bin bs=1K count=12
  fi
}

run

export RUST_LOG=debug
cargo run --example base -F destination_fs
