on:
  push:
    tags:
      - "*.*.*"
    branches:
      - master

name: Build and Release

jobs:
  ship-docker-image:
    environment: build-ship
    runs-on: ubuntu-22.04

    permissions:
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Acquire Docker image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            proseim/prose-pod-server
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=edge

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
          platforms: |
            linux/amd64
            linux/arm64

  create-github-release:
    needs: ship-docker-image
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Release new version
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.current_tag.outputs.tag }}
          body: "⚠️ Changelog not yet provided."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
